"""add ai usage tracking to users

Revision ID: 91d272c529b1
Revises: 3bd9431b8308
Create Date: 2026-08-11 17:01:11.192722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d272c529b1'
down_revision: Union[str, Sequence[str], None] = '3bd9431b8308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_message_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('ai_usage_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_usage_date')
    op.drop_column('users', 'ai_message_count')
    # ### end Alembic commands ###
