"""add seller role and product ownership

Revision ID: c1770a2db665
Revises: a0d3898f445e
Create Date: 2026-07-23 18:25:23.532208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1770a2db665'
down_revision: Union[str, Sequence[str], None] = 'a0d3898f445e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('discount_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'discount_price')
    op.drop_column('products', 'owner_id')
    # ### end Alembic commands ###
