"""drop promotion description

Revision ID: f46637ba5e06
Revises: 768d4d7a3ea9
Create Date: 2026-07-31 18:58:25.515704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46637ba5e06'
down_revision: Union[str, Sequence[str], None] = '768d4d7a3ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
